function createData(
  patientId,
  username,
  password,
  name,
  dob,
  gender,
  phoneNumber,
  email,
  address,
  anammesis,
  familyHeathHistory,
  hasAccount,
  examinationTimes
) {
  return {
    patientId,
    username,
    password,
    name,
    dob,
    gender,
    phoneNumber,
    email,
    address,
    anammesis,
    familyHeathHistory,
    hasAccount,
    examinationTimes,
  };
}

const rows = [
  createData(
    0,
    "thangws",
    "heehee",
    "Thang",
    "02/04/1999",
    "nam",
    "0288277348",
    "thang@thang.com",
    "trai ca, truong dinh",
    "can thi, thieu mau nao",
    "mau kho dong",
    "Y",
    4
  ),
  createData(
    1,
    "",
    "",
    "Thang1",
    "22/08/1999",
    "nam",
    "018646789",
    "thang@thang.com",
    "trai ca, truong dinh",
    "can thi, thieu mau nao",
    "mau kho dong",
    "N",
    7
  ),
  createData(
    2,
    "thangws",
    "heehee",
    "Thang2",
    "16/05/1999",
    "nu",
    "0888456789",
    "thang@thang.com",
    "trai ca, truong dinh",
    "can thi, thieu mau nao",
    "mau kho dong",
    "Y",
    1
  ),
  createData(
    3,
    "thangws",
    "heehee",
    "Thang3",
    "02/04/2000",
    "nam",
    "069356789",
    "thang@thang.com",
    "trai ca, truong dinh",
    "can thi, thieu mau nao",
    "mau kho dong",
    "Y",
    2
  ),
  createData(
    4,
    "",
    "",
    "Thang4",
    "02/07/1999",
    "nam",
    "0127568789",
    "thang@thang.com",
    "trai ca, truong dinh",
    "can thi, thieu mau nao",
    "mau kho dong",
    "N",
    15
  ),
  createData(
    5,
    "thangws",
    "heehee",
    "Thang5",
    "23/04/1999",
    "nu",
    "0123456559",
    "thang@thang.com",
    "trai ca, truong dinh",
    "can thi, thieu mau nao",
    "mau kho dong",
    "Y",
    4
  ),
];

export default rows;
